server:
  port: 12345

spring:
  datasource:
    url: jdbc:mysql://192.168.88.130:3306/ellen_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useAffectedRows=true
    username: ellen
    password: ellen
    driver-class-name: com.mysql.cj.jdbc.Driver

  # rabbitmq 配置
  rabbitmq:
    host: 192.168.88.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /